parameters:
  python_versions : []

steps:
  - ${{ each py_version in parameters.py_versions }}:
    - task: usePythonVersion@0
      inputs:
        versionSpec: '3.6'

    - checkout: self
      clean: true

    - script: python3 -m pip install --user pyyaml
      displayName: 'Install PyYaml'

    - script: python3 jellyfin-kodi/.config/generate_xml.py ${{ py_version }}
      displayName: 'Create ${{ py_version }} addon.xml'

    - script: zip -r plugin.video.jellyfin-${{ py_version }}.zip jellyfin-kodi
      displayName: 'Create ${{ py_version }} zip file'

    - script: ls .
      displayName: 'home dir 2'

#    - task: CopyFilesOverSSH@0
#      displayName: 'Upload to repo server'
#      inputs:
#        sshEndpoint: repository
#        sourceFolder: '${Agent.BuildDirectory}'
#        contents: 'plugin.video.jellyfin*'
#        targetFolder: '/srv/repository/incoming/kodi'
#
#    - task: SSH@0
#      displayName: 'Add to Kodi repo'
#      inputs:
#        sshEndpoint: repository
#        runOptions: 'inline'
#        inline: 'python3 /usr/local/bin/kodirepo add /srv/repository/incoming/kodi/plugin.video.jellyfin-version-${ py_version } --datadir /srv/repository/releases/client/kodi/${ py_version }'
