name: On PR Merge

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  trigger_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-prep') }}
    steps:
      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.9.1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          git config user.name "jellyfin-bot"
          git config user.email "team@jellyfin.org"

          VERSION="$(yq e -M '.version' release.yaml)"

          git tag v${VERSION}
          git push origin v${VERSION}
