name: Release Drafter

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5.15.0
        with:
          publish: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
